### PR TITLE
add docker setup and pin some dependencies

### PR DESCRIPTION
**Pull request by cenk1cenk2**
Hey @Salamek,

I have added a docker container as discussed on #5. To enable doing that I had to pin some dependency versions but no matter what I have tried I have failed to run this in a container otherwise. `pycrypto` was also one of them, as mentioned on issue #31 it worked with a direct replacement of `pycryptodom`. Please tell me if I am missing something as in the case of dependencies.

The container runs the API, Celery controller, and Celery Background task inside one container. RabbitMQ and Redis are also integrated into the container itself since they have no configuration to point to external servers. But for the scale of the application, I guess it is not that important, so I did not extend the config and this MR. The API is being run through the UWSGI socket to the Nginx socket as suggested. Everything runs on an unprivileged user account as suggested.

With this pull request:
- Update the documentation for pointing to the docker container.
- Pin some dependency versions to get this working on a container.

### CODE REVIEW

**Comment by Salamek** [comment]
Hi, i did bunch of refactoring to use more sane deps and to be compatible with Debian 11

**Comment by cenk1cenk2** [comment]
Hey @Salamek ,

Thank you for your work on this again! I have updated the container accordingly and moved it to Debian 11 Bullseye.

I still encountered one little problem with the `jinja` version `flask` uses and `markupsafe`. But pinning the version of `markupsafe` safe solves it. Hope it is an acceptable solution. Also, latest `jquery` that was updated by Dependabot was not acting right with the given version of `bootstrap` so I had to also revert it back to `3.4.1`.

Everything works a charm now. I will change the docker configuration to point to this repository with a specific commit if you accept my changes.

**Comment by Salamek** [comment]
Looks good to me!, Merging....

**Comment by Salamek** [comment]
Oh also in [your README.md ](https://github.com/cenk1cenk2/docker-gitlab-tools/blob/main/README.md)

> Due to complications, this application runs on an old version of Debian and Python, but it should cause no problems since this application is designed with it.

This^ no longer applies i think...

**Comment by cenk1cenk2** [comment]
Thanks for your time on this maintaining this again Salamek. I have updated the README accordingly.

**Pull request merged**
